name: Deploy to Hostinger KVM

on:
  push:
    branches:
      - production  # Adjust this to the branch you want to trigger deployment from

jobs:
  deploy:
    name: Deploy Changes to KVM Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Hostinger KVM
        run: |
          ssh -v -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} "
          cd /var/www/node-api &&
          git pull origin production &&
          npm install && # Remove or replace if you're not using Node.js
          pm2 restart api-server" # Replace with your actual server restart command, e.g., Apache or Nginx reload
