name: Deploy to KVM Production

on:
  push:
    branches:
      - production

jobs:
  Deploy-KVM-Prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_deploy
        chmod 600 ~/.ssh/id_rsa_deploy
        ssh-keyscan -H ${SERVER_HOST} >> ~/.ssh/known_hosts
        ls -la ~/.ssh
        echo "First 100 characters of id_rsa_deploy:"
        head -c 100 ~/.ssh/id_rsa_deploy
        echo "Last 100 characters of id_rsa_deploy:"
        tail -c 100 ~/.ssh/id_rsa_deploy
        echo "Complete SSH key content (truncated):"
        cat ~/.ssh/id_rsa_deploy | head -c 400
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}

    - name: Sync files to server using SSH
      run: |
        rsync -avz --delete ./ ${SERVER_USER}@${SERVER_HOST}:${SERVER_DIR}
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_DIR: ${{ secrets.SERVER_DIR }}

    - name: Install dependencies and restart the app on the server
      run: |
        ssh -i ~/.ssh/id_rsa_deploy -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_HOST} << 'EOF'
          cd ${SERVER_DIR}
          npm install
          pm2 restart node-api
        EOF
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_DIR: ${{ secrets.SERVER_DIR }}
